### PR TITLE
Not set if the hash value of the plug-in setting is "undef".

### PR DESCRIPTION
**Pull request by sugy**
- e.g. it can be used when overwriting with hiera.

### CODE REVIEW

**Comment by tnmt** [comment]
Hi @sugy.

Could you explain some examples about overwrite with hiera?

**Comment by sugy** [comment]
Hi @tnmt

I'm sorry it took a long time to reply.
For example, suppose you want to remove the linux plugin configuration for only `foo.example.com` node.

Configure hierarchy in hiera.yaml.

```yaml
# hiera.yaml
---
version: 5

hierarchy:
  - name: "Per-node data"
    path: "nodes/%{trusted.certname}.yaml"
  - name: "Common data"
    path: "common.yaml"
```

Set the merge behavior of mackerel_agent::metrics_plugins in lookup_options to hash.
Use common yaml to set up a linux plugin and fluentd plugin for all nodes.

```yaml
# data/common.yaml
---
lookup_options:
  mackerel_agent::metrics_plugins:
    merge: hash

mackerel_agent::metrics_plugins:
  linux: "/usr/bin/mackerel-plugin-linux"
  fluentd: "/usr/bin/mackerel-plugin-fluentd"
```

Override the linux plugin setting to null for `foo.example.com` node's yaml.
Setting it to null removes the linux plugin setting from config file on `foo.example.com` node.

```yaml
# data/nodes/foo.example.com.yaml
---
mackerel_agent::metrics_plugins:
  linux: ~ ## null
```

If you have a smarter way to do this, I'd be happy to hear about it.

**Review by tnmt — APPROVED** [review]
thank you for explain. it makes me clear about use case.

**Comment by sugy** [comment]
Thanks. I'll merge this PR since it got approval.

**Pull request merged**
